#+TITLE: Linear Algebra Assignment 5
#+AUTHOR: 2024110144
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper,12pt]
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+LATEX_HEADER: \pdfcompresslevel=9
#+OPTIONS: \n:t toc:nil num:nil date:nil

#+begin_center
Please submit by 5:00 PM on May 16th to the email address: 2592793289@qq.com
#+end_center

* Problem 1
Let $L: \mathbb{R}^3\rightarrow \mathbb{R}^2$ be defined by
$$L(x_1,x_2,x_3)=(2x_1-x_3,x_2+3x_3)^T$$.
1. Prove that $L$ is a linear transformation using the definition.
2. Find the standard matrix representation $A$ of $L$.
3. Calculate $L(1,-2,3)$ using matrix $A$.
** Solution 1
suppose $\vec{u}=x_1\vec{i}+x_2\vec{j}+x_3\vec{k}$, $\vec{v}=y_1\vec{i}+y_2\vec{j}+y_3\vec{k}$
we have
$$\begin{align*}
L(\vec{u}+\vec{v})
&= L(x_1+y_1,x_2+y_2,x_3+y_3)\\
&= (2x_1+2y_1-x_3-y_3,x_2+y_2+3x_3+3y_3)^T\\
&= (2x_1-x_3,x_2+3x_3)^T+(2y_1-y_3,y_2+3y_3)^T\\
&= L(\vec{u})+L(\vec{v})
\end{align*}$$
also for real constant $c$
$$\begin{align*}
L(c\vec{u})
&= (2cx_1-cx_3,cx_2+3cx_3)^T\\
&= c(2x_1-x_3,x_2+3x_3)^T\\
&= cL(\vec{u})
\end{align*}$$
so $L$ is a linear transformation
to solve the equation $L(x_1,x_2,x_3)=A\cdot (x_1,x_2,x_3)^T$
we have the first column of $A$ as
$$L(1,0,0)=(2,0)^T$$
similarly, second is $L(0,1,0)=(0,1)^T$,
the third being $L(0,0,1)=(-1,3)^T$
so $A=\left(\begin{matrix}2 & 0 & -1\\ 0 & 1 & 3\end{matrix}\right)$
then we can use $A$ to calculate the $L(1,-2,3)$
$$\begin{aligned}
L(1,-2,3)
&= A \cdot (1,-2,3)^T\\
&= \left(\begin{matrix}2 & 0 & -1\\ 0 & 1 & 3\end{matrix}\right) \cdot (1,-2,3)^T\\
&= \left(\begin{matrix}2\times 1+0\times (-2)+(-1)\times 3\\
0\times 1+1\times (-2)+3\times 3\end{matrix}\right)\\
&= \left(\begin{matrix}-1\\7\end{matrix}\right)
\end{aligned}$$

* Problem 2
Consider the matrix
$$A=\left[\begin{matrix}
1 & -2 & 3\\
2 & -5 & 1\\
1 & -4 & -7
\end{matrix}\right]$$
1. Reduce $A$ to (reduced) row-echelon form.
2. Using your result in (1), find a basis for the column space of $A$.
3. Determine rank($A$).
** Solution 2
$$\left[\begin{matrix}
1 & -2 & 3\\
2 & -5 & 1\\
1 & -4 & -7
\end{matrix}\right]$$
$$\left[\begin{matrix}
1 & -2 & 3\\
0 & -1 & -5\\
0 & -2 & -10
\end{matrix}\right]$$
$$\left[\begin{matrix}
1 & -2 & 3\\
0 & -1 & -5\\
0 & 0 & 0
\end{matrix}\right]$$
$$\left[\begin{matrix}
1 & 0 & 13\\
0 & -1 & -5\\
0 & 0 & 0
\end{matrix}\right]$$
$$\left[\begin{matrix}
1 & 0 & 13\\
0 & 1 & 5\\
0 & 0 & 0
\end{matrix}\right]$$
since the RREF form of $A$ has pivots on column 1 and column 2
we know the basis of $A$ could be $\left[\begin{matrix}
1\\
2\\
1
\end{matrix}\right]$ and $\left[\begin{matrix}
-2\\
-5\\
-4
\end{matrix}\right]$
the rank is equal to the pivot count, which in this case, $2$.

* Problem 3
Let $B=\left{\left[\begin{matrix}1\\1\end{matrix}\right],\left[\begin{matrix}1\\-1\end{matrix}\right]\right}$ and $C=\left{\left[\begin{matrix}1\\0\\0\end{matrix}\right],\left[\begin{matrix}1\\1\\0\end{matrix}\right],\left[\begin{matrix}1\\1\\1\end{matrix}\right]\right}$ be basis for $\mathbb{R}^2$ and $\mathbb{R}^3$ respectively.
Let $L:\mathbb{R}^2\rightarrow\mathbb{R}^3$ be defined by $L(x)=(x_1,x_1+x_2,x_2)^T$.
Find the matrix $A$ representing $L$ with repect to bases $B$ and $C$.
** Solution 3
the basis of $B$ would become $(1,2,1)^T$ and $(1,0,-1)^T$ after transformation
suppose $A=\left(\vec{a},\vec{b}\right)$
then we want $\vec{a}\cdot C=(1,2,1)^T$, $\vec{b}\cdot C=(1,0,-1)^T$
which means $A=\left[\begin{matrix}-1 & 1\\1 & 1\\1 & -1\end{matrix}\right]$

* Problem 4
Let $L:\mathbb{R}^2\rightarrow\mathbb{R}^2$ be a linear operator with standard matrix representation
$$A=\left[\begin{matrix} 2 & 1\\ -1 & 3\end{matrix}\right]$$.
Let $B=\left{\left[\begin{matrix}2\\1\end{matrix}\right],\left[\begin{matrix}1\\1\end{matrix}\right]\right}$ be another basis.
1. Find the transition matrix $S$ from $B$ to the standard basis.
2. Compute the matrix $B$ representing $L$ with respect to $B$.
** Solution 4
to the standard basis
$S$ is just $B^T$, which is $\left{\left[\begin{matrix}2\\1\end{matrix}\right],\left[\begin{matrix}1\\1\end{matrix}\right]\right}$
use $L$ on the first and second columns of $B$
we have $A\cdot \left[\begin{matrix}2\\1\end{matrix}\right]=\left[\begin{matrix}5\\1\end{matrix}\right]$
and $A\cdot \left[\begin{matrix}1\\1\end{matrix}\right]=\left[\begin{matrix}3\\2\end{matrix}\right]$
then the first column should be expressed like the matrix first colum multiplying with $B$
giving $\left[\begin{matrix}4\\-3\end{matrix}\right]$
doing the similar thing to the second gives $\left[\begin{matrix}1\\1\end{matrix}\right]$
which means the transformation matrix is $\left[\begin{matrix} 4 & -3\\ 1 & 1\end{matrix}\right]$
* Problem 5
Let $L_1:\mathbb{R}^2\rightarrow\mathhbb{R}^3,\,L_2:\mathbb{R}^3\rightarrow\mathhbb{R}^2$ be linear transformation defined by
$$L_1(x)=\left[\begin{matrix}x_1+x_2\\x_1-x_2\\2x_1\end{matrix}\right],\quad L_2(y)=\left[\begin{matrix}y_1+y_3\\y_1-y_3\end{matrix}\right]$$.
1. Find the standard matrix representations $A_1$ and $A_2$ for $L_1$ and $L_2$.
2. Find the standard matrix representation of the composition $L_2 \circ L_1$.
** Solution 5
suppose the standard basis in $\mathbb{R}^2$ is $\left(e_1,e_2\right)$
the standard basis in $\mathbb{R}^3$ is $\left(e_1,e_2,e_3\right)$
since $L_1(e_1)=(1,1,2)^T$, $L_1(e_2)=(1,-1,0)^T$
we know $A_1 = \left((1,1,2)^T,(1,-1,0)^T\right)$
similarly, since $L_2(e_1)=(1,1)^T$, $L_2(e_2)=(0,0)^T$, $L_2(e_3)=(1,-1)^T$
we have $A_2 = \left[\begin{matrix} 1&0&1\\1&0&-1 \end{matrix}\right]$
suppose the input is $\left[\begin{matrix}x_1\\x_2\end{matrix}\right]$
we know
$$\begin{aligned}
L_2 \circ L_1 (\left[\begin{matrix}x_1\\x_2\end{matrix}\right])
&= L_2 \circ \left[\begin{matrix}x_1+x_2\\x_1-x_2\\2x_1\end{matrix}\right]\\
&= \left[\begin{matrix}3x_1+x_2\\-x_1+x_2\end{matrix}\right]\\
&= \left[\begin{matrix}3&1\\-1&1\end{matrix}\right]\left[\begin{matrix}x_1\\x_2\end{matrix}\right]
\end{aligned}$$
so the standard matrix representation is $\left[\begin{matrix}3&1\\-1&1\end{matrix}\right]$
