#+TITLE: 脱盐复合膜研究进展
#+AUTHOR: 2024110144 陈有骏
#+LATEX_COMPILER: xelatex
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper,10pt]
#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+LATEX_HEADER: \usepackage{xeCJK}
#+OPTIONS: \n:t toc:nil num:nil date:nil

* 什么是脱盐复合膜？
鉴于从海水中提取淡水的需要，人们试图用精心构造的膜来替代传统方案，以期更加高效。

为了提高膜的过滤效率和寿命，采用复合膜结构。

要过滤靠活性层，要寿命靠支持层。

所以复合膜一般由多个活性层以及支持层组成。

* 方向
目前多从类似石墨稀的地方下手，都是研究不同纳米微观结构对过滤效果的影响。

当然，光有碳结构是不够的，人们还要从制备方法上研究。

制备结束后还可以通过特殊涂层提高寿命或者对盐分的排斥性。

* 复杂点

- 不同水质，膜的表现并不相同
- 经济、可持续性因素
  人们，准确说是研究员，不得不考虑用膜过滤海水的花销和收益
- 寿命和效果的平衡

诸如此类，还有很多。

* 进展
** 结构
通过纳米材料支持，改变表面及内部结构。研究人员尽量让水通量增大，盐排斥加强，来提高膜的效率。
除了这些新型材料，基体也是研究对象，人们试图找到化学性质更优的聚合物作为膜的基础材料承载那些物质。
这些聚合物多是一些带有亲水基团的化合物高分子，它们可以减少膜表面的污垢杂质。
当然，随着人工智能的发展，科学家也希望开发出智能材料，在不同环境下改变自身结构以保持更高效的运作。
** 制作
目前有界面聚合、相转化、溶液浇铸、自组装技术等制作方法。

其中自组装最为优质，但效率低，不适合工业化生产。另外三个都可以大批量生产，但是对制备过程和环境控制有不同的要求。

这里的研究目标也集中在保证微观结构的有效性上，膜太薄太厚都是不好的。
** 回收利用
如果可以回收利用，相当于降低了生产成本。

目前主要是再生膜。

问题是通过现有办法（化学药剂泡，冲洗，加热分解有机物）清理过的膜效果会差很多，如何让膜尽可能保持原有性质是这方面研究者的课题之一。

* 总结
试想一下，在荒岛上，不用蒸馏，只要拿个膜过滤一下海水就可以喝，岂不是很好？

现在人类面临水资源短缺的问题，未来还会更加严重，这方面的研究自然是非常有意义。

但我们也不能寄希望于海水变淡水，因为问题的本质是对水资源的污染和浪费而不是海水可不可以喝。

* 附录
事实上，这种膜作用很多，甚至可以用于医疗，并不局限于过滤淡水。

只是过滤海水是宏观上非常重要的，而且我们提不提其他用途也没有多少区别。

不论你怎么想，都不要认为它只能做什么，因为技术是中性的，是人赋予它用途。
