#+TITLE: 关于李约瑟难题的认识与看法
#+AUTHOR: 2024110144 陈有骏
#+LATEX_COMPILER: xelatex
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper,10pt]
#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+LATEX_HEADER: \usepackage{xeCJK}
#+OPTIONS: \n:t toc:nil num:nil date:nil

#+begin_comment
ddl: May 26th
#+end_comment

* 李约瑟难题
英国生物化学家李约瑟在其著作《科学与文明在中国》中指出，中国在古代有许多重大的科学技术发明，如火药、印刷术、指南针和造纸术等。然而，尽管中国在这些领域取得了显著成就，但在近代科学革命时期（大约16世纪至18世纪），中国却没有像西方国家那样发展出现代科学体系。李约瑟难题因此提出：为什么中国在科学技术上曾经领先，但在现代科学的形成和发展上却落后于西方？

** 影响
在李约瑟提出这个历史与哲学问题后，引发了人们很广泛的讨论。
事实上，直到今天，李约瑟难题依然是相关领域的热门研究话题。

* 对问题的认识
李约瑟问题比较的是古代中国和近现代西方，那么我们本着问什么答什么的态度，就不可以转而回答现代中国何以领先于现代西方。
而是说，为什么在中国人民创造力不输（实际上从李约瑟的前提，是远超）西方人民的情况下，古代中国却在现代科学发展上落后于西方了呢？
或者说，是什么让原本远落后于东方文明的西方世界“弯道超车”，在近现代科学发展上胜过了古代中国呢？

* 看法
我认为，这其中固然有西方自身自启蒙运动、撤去教会权力、从君主专制走向君主立宪等因素，但其根本要素还是古代中国的制度体系落后又死板
把自己给拖输了
在西方停留在君主专制时期还能靠天时地利成就“四海来朝”的美梦，但是当别人的科学不再被君主意志左右，而是（相比于在国王+教会大于一切的情况下）比较自由的发展时
还坚持君主专制的古代中国渐渐的就力不从心了
或者说掌舵的人本来就没有那个上进心。
这是可以理解的，说是万寿无疆，其实皇帝、大臣都明白不就活个几十年吗？
#+begin_quote
有钱就是挥霍
有权当然享乐
#+end_quote
这是人之常情（当然，不代表这是正确的）。
你看，中国古代大大小小的改革，有什么区别？
大前提都是别碰皇家蛋糕，莫动贵人饭菜。
结果是发明千千万，和人民没关系，藩属国数不清，抱歉，你农民不准随意出村，跟你也没关系。
你看，中国古代各式各样的发明，有什么区别？
大框架都是玩的用的，很少有真正利于群众的。
指南针是可以航海，但是在禁止人口流动的古代中国和人民有多大关系？
地动仪是可以测地震，但那段时间，怕是只够地主转移。
真正有用的也有，像黄道婆的纺织机器，农民用的犁啊水车啊之类的，但这些真的是中国专属吗？
恐怕不然，劳动人民的智慧世界无差，李约瑟和一众外国人所惊叹的古代中国智慧也都所指一些取悦专权的玩具。
不是说那些发明本身无用，它们在现代中国很有用，能上天入地，但是在古代中国的环境下，就难以称之为有用了。
即便是怎么说都是有用的研究，比如研究圆周率之类的，但试问，当时是当数学家的多还是“考公”的多？
我看不用我回答吧，个别的天才彰显了“是金子在哪都发光”的道理，那么又有多少是偏偏被深埋的沙金呢？
又有多少是没有那种天才，但本着三个臭皮匠，顶个诸葛亮的道理，本可以发光做出贡献的呢？
不计其数。
有人可能会奇怪，四大发明怎么就是取悦专权的玩具了？
首先，你要知道，现在的语境是古代中国何以落后，不要潜意识去想四大发明在当下现代中国的意义。
其次，我一一给你看。
1. 火药
   火药是啥？做鞭炮烟花的！
   有人可能会说，没有把火药做成武器，体现了中国人民的淳朴善良。
   呵呵，这种人要是放在古代中国，必然是佞臣小人，这明显是在为权贵洗白嘛。
   此话怎讲？
   火药作为一种爆炸物，本就有天生的攻击性。
   依照传说，火药做成鞭炮可以驱赶年，你看年在这个故事里怎么就这么十恶不赦？
   不是”苛政猛于虎“吗？
   这年又是什么来头？不会真有人信古代有山海经里那些怪奇之物吧！
   你看，年来的时间是不是和年终税收的时间相近，恐怕不是巧合。
   那么，为啥那种人是小人呢？
   你有没有发现，有一类人，在描述沉默的羔羊式群众时，毫不吝惜溢美之词，但一讲到Robin式群众时，就开始一副”诸位，我们要理智啊“的嘴脸来
   这种人固然没有直接当哈巴狗来的惹人生厌
   但是我恰恰认为他们是最可怕的，因为数量最多
   因为他们潜意识里就对权力心生向往，只是没有机会作恶罢了
   一旦得到机会，参考袁世凯，可能还不如袁大头呢！
   那么火药本身就有武器性质，不论是否塞到一个筒子里往一个方向打，为啥古代权贵要宣传其娱乐性质呢？
   第一，他们自己享受这种威慑感。
   第二，开民智则损君威（后面还有半句，立法度则失官意，但和我这篇文章无关，算了）。
   解释一下第二句，我们知道，不仅仅枪可以杀人，菜刀可以砍人，枕头也可以蒙死人，手可以掐死人，甚至你给人往栏杆上一怼，还能弄出内出血不治身亡或者截瘫在床
   可以说，杀人伤人方法千千万，但是有的确实更加高效。
   比如说冷兵器到热兵器。
   其实啊，对于国家与国家之间，只要横向比较，都是冷兵器和都是热兵器差别不大（对最终结果而言，此处不考虑对士兵、百姓造成的损害）。
   真正变化大的是“张献忠”，你觉得是拿把餐刀上街危害大呢还是提把冲锋枪上街危害大？
   也就是说，对于古代中国而言，只要武器比周边国家好，比普通民众好就可以，而不能一昧追求强大。
   更别说皇帝害怕武将倒戈了。
   所以说国家层面不去将火药武器化，或者他们仅在不得不研制更强大武器时探索火药可能。
   那为啥西方拿火药做武器呢，除了我懒得理会的”西方民众凶残“的理由，就是他们本身群体力量弱，不得不去研究更高效的武器。
2. 印刷术
   这东西好，可惜99%的资源都用来印皇家士大夫的东西了
   沦为了给权贵降低成本的工具，仅仅是顺带着让民间幸福指数提升，是的，我说的就是小人书。
   可以说技术是中性的，但是……你懂的。
3. 指南针
   还需要重复吗，航海与民众无关，加上当时禁止随意流动，基本是你拿到也用不上。
   这期间的科学技术提升，文科素养抬高，都可以类比教会统治时期的欧洲，也不是没有进步，但都在落后的大前提下进行。
4. 造纸术
   和印刷术一样。

** 辩白
有人可能奇怪了，为啥要体现人民意志才叫有用呢？
我告诉你，不是一定这样，而是基本上都是这样。
这是因为人各有欲，行事必然向自己喜好的方向倾斜。
这是人性的缺陷，我觉得没有办法克服，当然你非说某某是圣人，我也不和你强。
或者说大多数人都会倾斜自己的喜好吧！
事实上，没有人知道自己当下的决定是不是有用的
那我们如何做出尽可能有用（指事后看来有意义，不后悔）的决定呢？
四个字，集思广益。
这四个字你可别小看，往小了说是我做事参考别人观点，往大了说就是所谓的民主啊。
但是你要知道，这个词本身仅包含收集信息和处理的过程，不包含最终决定。
也就是说，做到集思广益，可以避免蒙蔽，不能防止一意孤行。
但实际操作时，能避免蒙蔽的都是少数，更别提不一意孤行了。
绝大多数人甚至不会去考虑集思广益，“三言四拍”放在许多人身上，都非常合适呢。
什么，哪三言，哪四拍？
#+begin_quote
三言四拍

第一言，对上司溜须拍马
第二言，对情人花言巧语
第三言，对下属连蒙带骗

第一拍，拍大腿决定
第二拍，拍胸脯保证
第三拍，拍脑袋坏事
第四拍，拍屁股走人
#+end_quote
哈哈，温馨提示，请不要对号入座。
真正的问题在于，对于群体越有利的事情，往往对持有优势权力的个人越不利，这在集权场景下最为明显
这就是为什么，古代中国的许多科技没有利于人民，用处就不大。中间逻辑我就跳了这么一层，故意的，懒得细讲。
假设外星人给古代中国安全的可控冷核聚变、任意精度的芯片制造技术等等一系列现在人类只能在科幻小说里想想的东西，你觉得古代中国能不能第一个造出载人飞船飞向外太空
我看，不可能！就算他们拿到永动机，也只会做成走马灯，或者墓穴机关。

* 后记
李约瑟的问题因为涉及到哲学和历史，可以讲的非常多
属于是公说公有理，婆说婆有理的类型
我这里就是从政治和人性的角度做一个剖析，难免有个人局限性，如有离谱之处，请一笑了之
李约瑟问题就聊到这里，我们江湖再见。
