#+TITLE: 温饱思淫欲，淫欲谁负责
#+AUTHOR: 2024110144 陈有骏
#+LATEX_COMPILER: xelatex
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper,10pt]
#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+LATEX_HEADER: \usepackage{xeCJK}
#+OPTIONS: \n:t toc:t num:t date:nil

#+begin_center
论改革开放以来深圳的变化之 +副作用+
#+end_center

* 被时代推上风口浪尖的渔村

看到我的题目，自然有人奇怪，到底我是要谈改开，还是谈深圳，还是谈变化，还是谈副作用。

这是可以理解的。

其实呢，这是大学政史课的一次课后作业，要求主题是“改革开放以来深圳的变化”。

我能说什么呢，当然是变化带来的问题了。夸赞没听够的话，自己去翻官微甚至兔友的推文嘛，懒得重复。

有人又要说，你的，改开后深圳蒸蒸日上一片向好，哪有什么问题？即便你真的感觉有问题，也是你自己的问题，深圳和改开都好得很！

有没有人看到我的题目和题注想这么说的？有的举手！

OK，我这篇文章要讲的问题，就是现在举手的或者准备这么说却耍滑头没举手的人。

这当然不是改革开放的错，也不是深圳的错，因为改革开放目的是发展经济而不是治理伪左，仅仅作为执行实验地点的深圳就更谈不上了。

有意思的是，我这篇文章要讲的其实也不是伪左，而是深圳改开成功发展经济后的当地群众，他们钱包鼓起来，却遭到了副作用的危害，极端表现才是伪左。

昔日默默无闻的渔村啊，你在时代的安排下造就奇迹，成为世界一流城市，却少有与之匹配的内蕴涵养。

* 假如给你一个亿

假如给你一个亿，你会做什么？

且慢，先别想，免得等下又被我预判骂到。

我记得几年前有个非常流行的白日梦，它大概是这样。

#+begin_quote
如果我有一个亿，就存到银行，每年能有十来万利息，还工作干啥，舒舒服服的躺一生。
#+end_quote

好不好？很好，如果有个稳定的一年十万而不需要我任何付出的收入来源（具体如专利，版费之类的东西，不考虑父母），我也美滋滋的躺一生。

但问题在于，你拿到了每年花100万，能花100年的钱，不特别挥霍纯享乐的话可以说到死都花不完。

结果你的梦想却是把这么多钱给银行，每年靠一二线城市白领常见的一年10万左右生活，就挺好笑的不是么？

有人可能会说，不一样啊，存银行过一百年我还是有一亿存款，这个10万一年是无限的 *稳定* 收入，我也明白用的话一年100万都花不完，但是钱越用越少了啊。

大家觉得这种想法对不对？

很对，很有道理，但问题在于你存到银行就真的 *稳定* 了么？恐怕不是。

科普一下，世界上是有银行不给你利息，反而要你给它交利息的。现在我们用这个知识再来看你的所谓收入。

为什么银行要给你利息，因为你的本金在存放期间会被挪用！说“挪用”有点难听，因为这里是你授权的，可惜我也找不到其他意思贴切的词，就不换了。

简单来说，为啥你存一点钱银行要给你利息，就是它拿着你的钱能做更有价值的事，让它产生更多钱，比方说，放贷，只是打个比方。

你为什么要把钱存到银行，还不是你没有比存银行更体现这些钱价值的去处么？

为什么有的人中奖几万反手换了新手机在微博上炫耀，有的人断炊了还借几千块只为让展柜再摆一天？

这叫什么，这叫眼界。

眼界怎么提高，靠冥想和看书都没用，只能实操，至少看身边人实操。

如果你身边的人拿到钱就648、648的充，36、36的月卡续费，你或许也会如此，认为648就相当于顶级宝箱100连抽。

如果你身边的人除了国内视频会员啥也不订购，你很可能就会认为每年200多的视频会员相当于国内影视自由。

如果你身边的人动不动手办、盲盒，你或许就将100与一次抽奖挂钩。

不论高低，现在你手上有点钱可以花的话，必然会花在自己潜意识挂钩的地方。而不幸的是，我们无法看见眼界之外的事物，可以说环境咋样人就咋样。

古人说近朱者赤近墨者黑是有道理的。

注意，这里并不是说充648就比买手办坏，没有高低贵贱，只是认识到人是环境的产物。

我也是这样，最近在看建站方面的内容，所以有钱就想租个服务器什么的，而不是买奶茶喝。

所以你给我30，可能我就租了两三周vultr那个5美元1月的套餐，而不会主动去考虑其他花销。

但一个月 *5美元* _1核1G内存2T流量_ 的实例我拿来搭个连搜索引擎都 *不收录* ，CPU负荷没到过 /10%/ ，一个月还没跑到 /1MB/ 流量，唯一利用率高的是内存的博客到底值不值得，

说实话，从钱方面考虑不值，但好玩，就像有人打麻将不是为了赢钱，有人氪金不是为了皮肤，我赔本建站自然也不是为了流量变现。

至于好不好，不知道，这就是人在特定环境下的局限性。

* 没机会作恶的悲惨不值得同情

曾经有过一个社会实验，我听说的，说是欧洲什么人在非洲的某个小地方划了块地实验民主制度。

结果还没到一个月就血流成河了。

倒没有找到过原文，估计是网友瞎编的，但是这个故事却非常合理。

冻伤的人不能立即烤火甚至要先泡冷水，重病的人不能下强效药否则可能一命呜呼，同样，对着封闭落后的地区说投票表决就会导致一片混乱。

这里有一点需要辩明，虽然我举的例子是伤病与治疗，但并不是暗示民主就比集权优越，或许换个中立的例子更好，但我懒得删，就不换了。

为什么举伤病例子呢？因为实验实施者是欧洲人嘛！他为啥在非洲做民主实验，自然是认为民主比当地的制度更优越，懂了么。换位思考。

本文倒不关心之间的利害，只是指出背后逻辑。

为什么大变动是不好的？请看本段标题，试回答，“可怜之人必有可恨之处”有没有合理性？

因为他们性子一模一样，只是有的刚好出生高位，有的刚好出生卑微罢了！

世人都说秦始皇残暴，建长城累死无数民工，但就冲网文上穿越重生当皇帝的热度，恐怕大多数人根本没有权利笑话嬴政吧。

可别一百步笑五十步了。

随便在大街上抓个人模狗样的摁到秦一世龙椅上，怕是皇宫外建N道长城都不放心，真・孤家寡人。

虽然这里举的例子是权力，但你可别局限于权力，放在任何需要竞争的欲望上都适用。

* 靠一池弹珠搭不出通天巨塔

道德很重要，但这玩意很慢，甚至经常被忽视。

甚至有钱能使鬼推磨的话流传千百年不倒。

唯一一次我看到有人真的表达钱无用的场合，是动画片《蓝精灵》，我每次看都很感动，乌托邦不过如此。

说实话，问题不在于钱，那个只是载体，即便蓝精灵们要交换货币甚至电子支付，也可以保持纯洁。

问题在于人，准确说是社会平均道德水平。

*有人* 可能会说，你是想说深爷道德低下合着？

对此我要申明，我想说的只是这些拿着帽子准备扯大旗扣屎盆子的 *人* 道德低下，而他们数量之多，拉低社会平均道德水平。

你给蓝精灵金币，人家也不会稀罕，更不会明争暗斗。

但你往偏远乡村的巷子里丢块馒头，就可能有一群恶犬争抢，甚至有的试图恐吓你。

深圳的人们自然比蓝精灵强上千百倍，只是额外的喜好金币。

* 淫欲是温饱的错

终于推进到本文正题了，温饱思淫欲是谁的错？

我认为是温饱的错，准确说不是温饱本身的错，而是享受温饱的人本身的错。

内在逻辑是这样的：

1. 我没有错

   这是自然，我是作者嘛，哪会有错。

2. 温饱和淫欲本身都没错

   这也是自然，有错是要负责的，责任到人。

   这两个都是人的属性，总不能说“非我也，手也”吧。

3. 给你淫欲的来源未知

   天知道你脑子里装的是啥，咋负责，是吧。

4. 给你温饱的人没错

   这也是自然，人家让你吃饱穿暖，你自己欲求不满还赖别人头上，怎么都说不过去吧！

5. 排除法+总有人有错

   还剩下什么心里有数没？

话不投机半句多，我行文就到此为止。

戛然而止，很好，我们江湖再会。
