#+TITLE: Linear Algebra Assignment 8
#+AUTHOR: 2024110144 陈有骏
#+LATEX_COMPILER: xelatex
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper,12pt]
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+LATEX_HEADER: \usepackage{xeCJK}
#+OPTIONS: \n:t toc:nil num:nil date:nil

#+begin_center
Please submit by 5:00 PM on June 27th to the email address: 2592793289@qq.com
#+end_center

* Problem 1
Let
$$A=\begin{bmatrix}
4 & 0 & 0\\
2 & 2 & 0\\
0 & 2 & 2
\end{bmatrix}.$$
1. Compute the characteristic polynomia of $A$ and find all eigenvalues.
2. For each eigenvalue, determine basis for the corresponding eigenspace.

** Solution 1
*** 1
$$A-\lambda I=\begin{bmatrix}
4-\lambda & 0 & 0\\
2 & 2-\lambda & 0\\
0 & 2 & 2-\lambda
\end{bmatrix}$$
the determinant of this is
$$det = (4-\lambda)(2-\lambda)(2-\lambda)$$
so the eigenvalues are $4$ and $2$
*** 2
for eigenvalue $4$
the equation is $(A-4I)\vec{basis}=\vec{0}$
which means $\begin{bmatrix}
0 & 0 & 0\\
2 & -2 & 0\\
0 & 2 & -2
\end{bmatrix} \cdot \begin{bmatrix}
x\\y\\z
\end{bmatrix} = \begin{bmatrix}
0\\0\\0
\end{bmatrix}$
so we have the basis as $\begin{bmatrix}x\\x\\x\end{bmatrix}$ where $x\in\mathbb{R}$
for eigenvalue $2$
the equation is $(A-2I)\vec{basis}=\vec{0}$
which means $\begin{bmatrix}
2 & 0 & 0\\
2 & 0 & 0\\
0 & 2 & 0
\end{bmatrix} \cdot \begin{bmatrix}
x\\y\\z
\end{bmatrix} = \begin{bmatrix}
0\\0\\0
\end{bmatrix}$
so we have the basis as $\begin{bmatrix}0\\0\\x\end{bmatrix}$ where $x\in\mathbb{R}$

* Problem 2
Consider
$$B=\begin{bmatrix}
3 & 1\\
0 & 3
\end{bmatrix}.$$
1. Find the eigenvalues of $B$ and state their algebraic multiplicities.
2. Find the basis for each eigenspace and give the geometric multiplies.
3. Decide whether $B$ is diagonlizable. Briefly justify your answer in one sentence.
** Solution 2
*** 1
$$\begin{aligned}
det(B-\lambda I) &= det\left(\begin{bmatrix}
3-\lambda & 1\\
0 & 3-\lambda
\end{bmatrix}\right)\\
&= (3-\lambda)^2
\end{aligned}$$
so the eigenvalue is $3$, with the algebraic multiplicity as $2$
*** 2
for $3$
we have $\begin{bmatrix}0&1\\0&0\end{bmatrix} \cdot \vec{basis} = \vec{0}$
which yields the basis as $\begin{bmatrix}1\\0\end{bmatrix}$
with the geometrix multiplies (as the free variable of basis in RREF) $1$
*** 3
the algebraic multiplicity of $\lambda=3$ is $2$, while the geometric multiplicity is $1$.
Since these multiplicities do not match, the matrix $B$ is not diagonalizable.
* Problem 3
Let
$$C=\begin{bmatrix}
4 & 2\\
2 & 5
\end{bmatrix}.$$
1. Verify that $C$ is symmetric and compute its eigenvalues.
2. Find an orthonormal set of eigenvectors and form the orthogonal matrix $Q$ whose columns are these vectors.
3. Check that $Q^TCQ$ is diagonal and list the diagonal entries.

** Solution 3
*** 1
since $C=C^T$, it is symmetric
$$\begin{aligned}
det(C-\lambda I)
&= det\left(\begin{bmatrix}
4-\lambda & 2\\
2 & 5-\lambda
\end{bmatrix}\right)\\
&= 20-9\lambda+\lambda^2-4\\
&= \lambda^2-9\lambda+16
\end{aligned}$$
the eigenvalues are $\frac{9\pm\sqrt{17}}{2}$
*** 2
the corresponding eigenvectors are $\begin{bmatrix}4\\1\pm\sqrt{17}\end{bmatrix}$
their magnitudes are $\sqrt{34\pm 2\sqrt{17}}$
so $Q$ is $\begin{bmatrix}
\frac{4}{\sqrt{34+2\sqrt{17}}} & \frac{4}{\sqrt{34-2\sqrt{17}}}\\
\frac{1+\sqrt{17}}{\sqrt{34+2\sqrt{17}}} & \frac{1-\sqrt{17}}{\sqrt{34-2\sqrt{17}}}
\end{bmatrix}$
*** 3
$$\begin{aligned}
Q^TCQ
&= \begin{bmatrix}
\frac{4}{\sqrt{34+2\sqrt{17}}} & \frac{1+\sqrt{17}}{\sqrt{34+2\sqrt{17}}}\\
\frac{4}{\sqrt{34-2\sqrt{17}}} & \frac{1-\sqrt{17}}{\sqrt{34-2\sqrt{17}}}
\end{bmatrix} \cdot \begin{bmatrix}
4 & 2\\
2 & 5
\end{bmatrix} \cdot \begin{bmatrix}
\frac{4}{\sqrt{34+2\sqrt{17}}} & \frac{4}{\sqrt{34-2\sqrt{17}}}\\
\frac{1+\sqrt{17}}{\sqrt{34+2\sqrt{17}}} & \frac{1-\sqrt{17}}{\sqrt{34-2\sqrt{17}}}
\end{bmatrix}\\
&= \begin{bmatrix}
4\cdot\frac{4}{\sqrt{34+2\sqrt{17}}}+2\cdot\frac{1+\sqrt{17}}{\sqrt{34+2\sqrt{17}}} & 2\cdot\frac{4}{\sqrt{34+2\sqrt{17}}}+5\cdot\frac{1+\sqrt{17}}{\sqrt{34+2\sqrt{17}}}\\
4\cdot\frac{4}{\sqrt{34-2\sqrt{17}}}+2\cdot\frac{1-\sqrt{17}}{\sqrt{34-2\sqrt{17}}} & 2\cdot\frac{4}{\sqrt{34-2\sqrt{17}}}+5\cdot\frac{1-\sqrt{17}}{\sqrt{34-2\sqrt{17}}}
\end{bmatrix} \cdot \begin{bmatrix}
\frac{4}{\sqrt{34+2\sqrt{17}}} & \frac{4}{\sqrt{34-2\sqrt{17}}}\\
\frac{1+\sqrt{17}}{\sqrt{34+2\sqrt{17}}} & \frac{1-\sqrt{17}}{\sqrt{34-2\sqrt{17}}}
\end{bmatrix}\\
&= \begin{bmatrix}
\frac{18+2\sqrt{17}}{\sqrt{34+2\sqrt{17}}} & \frac{13+5\sqrt{17}}{\sqrt{34+2\sqrt{17}}}\\
\frac{18-2\sqrt{17}}{\sqrt{34-2\sqrt{17}}} & \frac{13-5\sqrt{17}}{\sqrt{34-2\sqrt{17}}}
\end{bmatrix} \cdot \begin{bmatrix}
\frac{4}{\sqrt{34+2\sqrt{17}}} & \frac{4}{\sqrt{34-2\sqrt{17}}}\\
\frac{1+\sqrt{17}}{\sqrt{34+2\sqrt{17}}} & \frac{1-\sqrt{17}}{\sqrt{34-2\sqrt{17}}}
\end{bmatrix}\\
&= \begin{matrix}
\frac{4(18+2\sqrt{17}) + (1+\sqrt{17})(13+5\sqrt{17})}{34+2\sqrt{17}}
& \frac{4(18+2\sqrt{17}) + (1-\sqrt{17})(13+5\sqrt{17})}{\sqrt{34^2-4\times 17}}\\
& \frac{4(18-2\sqrt{17}) + (1+\sqrt{17})(13-5\sqrt{17})}{\sqrt{34^2-4\times 17}}
& \frac{4(18-2\sqrt{17}) + (1-\sqrt{17})(13-5\sqrt{17})}{34-2\sqrt{17}}
\end{matrix}
&= \begin{matrix}
\frac{170+26\sqrt{17}}{34+2\sqrt{17}}
& 0\\
& 0
& \frac{170-26\sqrt{17}}{34-2\sqrt{17}}
\end{matrix}
&= \begin{matrix}
\frac{85+13\sqrt{17}}{17+\sqrt{17}}
& 0\\
& 0
& \frac{85-13\sqrt{17}}{17-\sqrt{17}}
\end{matrix}
\end{aligned}$$
so it is indeed diagonal and the entries are the two fractions

* Problem 4
Let
$$D=\begin{bmatrix}
0 & 3\\
4 & 0
\end{bmatrix}.$$
1. Compute the singular values of $D$ without fully diagonizing $D^TD$
   (hint: note the $D^TD$ is diagonal)
2. Give one unit right singular vector and one unit left singular vector corresponding to the largest singular value.
3. Write a compat $SVD$ of the form $D=U\sum V^T$ using your vectors from part 2 and the singular value from part 1.
** Solution 4
*** 1
$$D^TD=\begin{bmatrix}
16 & 0\\
0 & 9
\end{bmatrix}$$
indeed diagonal, meaning the eigenvalues being $16,9$
so singular values are $4,3$ which are the square root of eigenvalues.
*** 2
$$D^TD\vec{v}=eigenvalue\cdot\vec{v}
*** 3
* Problem 5
Using the $SVD$ obtained in Problem 4.
1. Construct the best rank-1 approximation $D_1=\epsilon_1\vec{u}_1\vec{v}_1^T$.
2. Compute the Frobenius norm of the error $||D-D_1||_F$ (note that this equals the second singular value).
3. In one or two sentences, explain why part 2 follows from the Eckart-Young(Th 6.5.3) theorem.

** Solution 5
