#+TITLE: Biochemistry

# 主要第4-7章

* Chapter 1
The Facts of Life
** 4 levels
| proteins                                | structures              | organisms | ecosystem |
| this is the basis                       | biomolecules controlled |           |           |
| lipids and carbohydrates also important | functional purposes     |           |           |
| but not basic                           |                         |           |           |
*** energy source sunlight
** What is life?
- Organisms complicated + hightly organized
- Biological structures serve functional purposes
- Living systems are actively engaged in energy transformations
- LIving systems have a remarkable capacity for self-replication

** Biomolecules
:example:
+ Nucleotide -> DNA/RNA
+ Amino acids -> protein
+ Carbonhydrates -> sugar
+ Fatty acid -> lipid
:end:
*** they all have "direction"
*** CHON
covalent bond共价键
这几个之间的共价键能量高，更稳定
** the Structual Organization of Complex Biomolecules
:example:
Cholesterol 胆固醇
$\beta$-carotene 胡萝卜素
Chlorophyll a 叶绿素
:end:
*** they have different sizes
** Properties of some important biomolecules
*** a sense or directionality
dna/rna 5'-3'
Protein: N-terminal - C-terminal
*** Informational
*** three dimensional architecture
*** biomolecular interactions
**** weak forces
Covalent bonds -> strong force
:example:
C-C bond 343kJ/mol
:end:

weak forces 0.4-40kJ/mol => decide which of them can form bonds
further *deside protein structure*

** the Organization and Structure of Cells

* chapter 2
** water
*** hydrophobic interaction
fatty acid in water as example
cage -> four becomes one, use less water molecules

**** hydrophobic interaction *decide*
1. which amino acid to be placed here or there
2. which protein to be set inside a cell or on the surface

*** the solvent properties of water derive from its polar nature

** pH
*** enzyme activity is influenced by pH
*** K_a酸度系数
$K_a=\frac{[H^+][A^-]}{[HA]}$
**** pK_a
加$p$就是$-log_{10}$
*** the dissociation behavior weak
** what are Buffers and what do they do

* chapter 4
Amino acids
** structures and properties of amino acids
四面体tetrahedral structure
必定有-NH_2（可能和H^+结合） amino group
必定有-COOH（可能失去H^+） carboxyl group

支链决定氨基酸是碱性还是酸性

:note:
alpha C means the C in middle of an amino acid
:end:

contain a central tetrahedral carbon atom
some amino acids are not found in proteins

the 20 common amino acids
S还是很重要（只用4种顶多16个）=> 启动子就是含S的氨基酸

ATCG
G用于转弯
有O和-NH_2时很可能是个偶极polar氨基酸

disulfide bridge二硫键 很稳定

** titrations of polyprotic amino acids
等电点
** Nucleophilic substitution reaction of carboxylic acids亲核取代反应
*** 亲核体（有机化学内容）
** reactions of amino acids
e.g. Edman reagent Phenylisothiocyanate aggrv. PITC
*** this edman degradation can be used to N-terminal protein sequencing
N端第一个氨基酸可以分离出来，叫PITC，和？？结合后叫PTH，可以得到第一个到底是什么
循环可以测序
*** 当两个-SH靠得很近，会发生氧化反应
生成-S-S-共价键
用于稳定蛋白的三维结构（单个多肽链自己钉起来学术来说是三级结构，当两个多肽链靠这个结合，就是四级结合）
*** Rules for Description of Chiral Centers in the R,S System逆时针还是顺时针
Right-handed -> D type
Left-handed -> L type
对称的是AA
*** Spectroscopic Properties
看UV吸收谱，蛋白质吸收谱在280，如果提取的DNA吸收谱在280有峰，说明样品被蛋白质污染了
** Seperation of amino acids
*** chromatography 色谱
1. stationary固定相
2. mobile phase
**** HPLC amino acid analysis
吸流，壁带有负电荷，这样不同氨基酸通过速度不同，可以分离
要取出带正电荷被吸住的氨基酸通过ION EXCHANG CHROMATOGRAPHY，添加更强的阳离子把氨基酸替出来，如NaCl溶液
*** NMR 核磁共振
** What is the Fundamental Structural Pattern in Proteins?
Peptide肽 的生成
多肽里有几个氨基酸，只要数-N-C_a-C_b-排列的个数
N is the amide nitrogen of the amino acid
C_a is the alpha cabon
C_b is
*** amino acids join via peptide bonds肽键
loss of a water molecule脱一个水分子
*** 肽键为何是一个平板结构
(false) a pure double bond between C and O would permit free rotation around the C-N bond
the true election density is intermediate
其有trans顺时针和cis逆时针两种摆法，使得即便它是固定的平板，氨基酸也可以动
就是顺逆时针的区别，这样需要的能量最少
*** Peptides
residue残基
dipeptide
tripeptide
oligopeptide
*** Protein
One polypeptide多肽 chain链: a monometic protein
more than one: multimeric protein(subunites)
Homomultimer: one kind of chain
Heteromultimer: two or more different chains
Tetramultimer: four or more different chains
**** Insulin 胰岛素
hexa- 六合
* Chapter 6
Protein
原意来自希腊海神，有不同形态出现
** outline
一级结构 Primary Structure - amino acid sequence
二级结构 Secondary Structure - folding of polypetide chain
三级结构 Tertiary Structure - 3D folding
四级结构 Quaternary Structure - interation of different polypeptide chain
** Protein Structure and Function are Tightly Linked
** What Noncovalent Interactions Stabilize the Higher Levels of Protein Structures
weak force
e.g.
van der Waals 0.4-4kJ/mol
hydrogen bonds 12-39kJ/mol
ionic bonds 20kJ/mol
hydrophobic interactions <40kJ/mol
*** secondary , tertiary and qua.. are formed and stablized by weak forces.
van der Waals is ubi..
*** Electrostatic interactions in Proteins
** What Role Does the Amino Acid Sequence Play in Protein Structure?
*** The meaning of $\delta H^\circ$
Unfolding process:
Native protein (N) to/from Denatured protein (D)
1. breaking of hydrogen bonds
2. exposure of hydrophobic groups
3. raise the energy of the solution
4. ..

** What are the elements of Secondary Structure in Proteins, ..
*** Dihedral Angles
The amide or peptide bond plans are joinded by the tetrahedral bonds of the $\alpha$-carbon
The rotation parameters are $\phi$ (N-ter) and $\psi$ (C-ter).
*They are decided by 支链*
肽键张角omega永远是180度，是个平面
后面的二级结构其实就是平面如何耦合，靠那个连接处的C
*** Classes of Secondary Structure 二级结构
Alpha helices
Other helices
Beta sheet (composed of "beta strands")
..
**** $\alpha$-helix
$\psi=-45^{\circ}, \phi=-60^{\circ}$
*stablized by H bonds*
H被氨拉走，本身桥有O，生成氢键
本身又有一个H和O，一共两个氢键
这也是靠支链来的，所以不是任何氨基酸结合都生成alpha helix
现在只是链内相邻的作用
***** numbers to know
3.6 residues per turn
1.5 Angstroms (0.15nm) rise per residue
:angstroms:
埃
量度单位，等于$10^{-10}$米，0.1纳米，表示波长之类的
:end:
..
***** exposed N-H and C=O groups at the ends of an alpha helix can be "capped"
**** $\beta$-Pleated Sheet
$\psi=130^{\circ}, \phi=-140^{\circ}$
大于90度，不转弯，拉得比较平
相邻条头尾是反的，这样O和H刚好更靠近，生成氢键。
这样相反的叫 *反平衡结构* ， 是氢键让它在生成链的转弯（可能是很大的"弯"）时将其稳住
***** Spider Silk
蛛丝蛋白就有这样的beta sheet结构
**** Alpha-turn
** how do polypeptides fold into three dimensional protein structures?
*** proteins fold so as to form the most stable structures
Formations of large numbers of intramolecular hydrogen bonds
Reduction in the surface area accessible to solvent that occurs upon folding
(not all aa are polar/hydrophilic, next slide)
** 三级结构
*** fibrous proteins
single axis
mechanically strong
**** Lys-Lys crosslinking
将所有核氨酸固定，只能在细胞外催化。
**** Collagen and bone formation
骨头去掉钙，剩下几乎都是胶原蛋白纤维，形成很多坑洞。
"hole regions"-they contain carbonhydrate..
**** Structural basis of the collagen triple helix
Interchain H bonds of HyP -> stabilizing
intrachain lysine-lysine and interchain hydroxypyndinium crosslinks (covalent bond)
*** Globular Proteins 一坨
Globular proteins much more than fibrous proteins
内部其实也有很多二级结构（如alpha helix和beta sheet）
**** some design principles
Helices and sheets make up the core of most globular proteins
Most polar residures face the outside
Most hydrophobic residues face the interior
Close association between aa
*empty space exists* because ratio of vander Waals' volume to total (actual) volume is only 0.72 to 0.77
The empty space is in the form of small cavities
空间可以用于接受底物之类的，而且它自身在振动，需要这些空隙
能量最低最稳定，暴露在外的疏水部分越少能量越低，除非有二硫键
内部的N-C-C骨架的稳定性靠二级结构的氢键反平衡结构来解决N的偶极问题
**** protein core versus protein surface
- core
  typically constant and conserved
  in different organisms
  in sequence and structure
- surface
  loops and turns that connect the helices and sheets of the core

a comlex landscape of different structure elements
intereact with small molecules or with other proteins
they are the basis for interactions:
+ enzyme-substrate interactions
+ cell signaling
+ immune responses (epitope抗原决定基)
+ ..

**** protein surfaces are complex

**** water and protein surface
- hydrophilic outside rule
- protein surface interact with water by H-bond

**** 蛋白质表面的二级结构
**** Diseases of Protein Folding

