#+TITLE: Linear ALgebra 
* linear system
- at least one solution
  consistent相容
  + all solutions
    solution set解集
- no solution
  inconsistent不相容
  solution set empty
** $2\times 2$ system
two lines have 3 possibilities
for solution set
1. one
   consistent
2. zero
   parallel
   inconsistent
3. infinitely many
   consistent
*** $m\times n$
m row n columns
read as "m by n"
if it is consistent, it must have either exactly 1 solution or infinite solutions
else it have 0 solutions.
** $n\times n$ systems
- this is a *square*
  because it has the same number of rows and columns
- If it has exactly one solution, then using op 1 and 3 -> strict triangular system
- Def
  A system is said to be in *strict triangular form* if, in the kth equation, the coefficients of the first k-1 variables are all zero and the coefficient of $x_k$ is nonzero $(k=1,...,n).
- /back substitution/
  1. the nth equation is solved for the value of $x_n$.
  2. This value is used in the (n-1)st equation to solve for $x_{n-1}$.
  3. The values $x_n$, $x_{n-1}$ are used in the (n-2)nd equation to solve for $x_{n-2}$
  4. so on ...
** Equivalent Systems
+ Def : two systems meeting following criterias
  - same variables
  - same solution set
+ 3 op
  1. The order of 2 eq can be interchanged
  2. both sides of an equation may be multiplied by any none zero real number
  3. a multiple of one equation may be added to (or subtracted from another)
** coefficient matrix系数矩阵
coefficient matrix of system
| 1  2  1 |
| 3 -1 -3 |
| 2  3  1 |
** argumented matrix增广矩阵
| 1  2  1 |  3 |
| 3 -1 -3 | -1 |
| 2  3  1 |  4 |
(A|B) B doesn't have to be 1 columned
*** elementary row operations初等行变换
1. interchange two rows
2. multiply a row by a nonzero real number
3. replace a row by its sum with a mutiple of another row
*** pivotal row主行 & pivot主元
The first row is called the pivotal row
it is used to eliminate the elements in the first column of the remaining rows
The first nonzero entry in the pivotal row is called the pivot
*** row echelo form行阶梯形
- Def
  1. first nonzero entry in each nonzero row is 1
  2. if row k does not consist entirely of zeros, the number of leading zero entries in row k+ is greater thant he number of leading zero entries in row k
     否则就不是阶梯了……
  3. if there are rows whose entries are all zero, they are below the rows having nonzero entries
- example
  #+begin_example
    | 1 4 2 |
    | 0 1 3 |
    | 0 0 1 |
    yes
    | 1 2 3 |
    | 0 0 1 |
    | 0 0 0 |
    yes
    | 2 4 6 |
    | 0 3 5 |
    | 0 0 4 |
    no
    | 0 1 |
    | 1 0 |
    no
  #+end_example
*** when will the method for $n\times n$ -> strict triangular form fail
when all the possible choices for a pivot element in a given column are 0
*** lead variables and free variables
For reduced matrix only
- lead
  the *first* nonzero elements in each row of the reduced matrix
- free
  the *remaining* variables corresponding to the columns *skipped* in the reduction process
*** Gaussian elimination
- Def
  the process of using row operations I II III to transform a linear system into one whose augmented matrix is in row echelon form is called Gaussian elimination
**** consistent or not?
if row echelon form of the augmented matrix contains a row of the form
| 0 0 0 ... 0 | 1 |
the system is inconsistent
otherwise, the system is consistent
*** overdetermined systems
- Def
  a linear system is said to be /overdetermined/ if there are more equations than unknowns.
- usually inconsistent
  but not always
*** underdetermined systems
must have infinite number of solutions
*** reduced row echelon form
1. it should be row echelon
2. the first nonzero entry in each row is the only nonzero entry in its column
*** homogeneous systems齐次的线性方程组
- Def
  右边全是0的线性系统
- 一定有解(all being 0)
  trival solution平凡解
** 1.3 matrix arthimetic
*** matrix notation
Capital letters ABC... to represent
use $a_{ij}$ denote the entry of the matrix A tat is in the ith row and the jth column
we refer to this entry as the (i,j) entry of A
*** vector
**** 行向量加横箭头，列向量只要加粗
**** Equality
- Def
  two $m\times n$ matrix A and B are said to be equal if $a_{ij} = b_{ij}$ for each i and j.
**** Scalar Multiplication
- Def
  If A is an $m\times n$ matrix and $\alpha$ is a scalar, then $\alpha A$ is the matrix formed by multiplying each of the entris of A by $\alpha$.
*** 0矩阵加任何矩阵A（一样大）都是A
*** matrix mutiplication and linear systems
**** 1
\begin{align}
Ax &= [ 1 2 5 ] \left [ \begin{align} a &\\ b &\\ c \end{align} \right ]\\
&= a + 2b + 5c
\end{align}
**** scalar标量 product
inner product内积（可导出范数），以后会学到外积（可看出哪部分数据最重要）
一个行向量乘一个列向量叫内积
**** linear combination线性组合
就是几个标量和向量乘积相加等于向量的等式
***** consistency theorem for linear systems
**** A mxn B nxr -> AB = C is mxr matrix
$C_{ij} = \vec{a_i} b_j = \sum_{k=1}^n a_{ik} b_{kj}$.
**** the identity matrix I
IA=AI=A
**** matrix reversion (逆)
If BC are both multiplicative inverses of A, then B=BI=B(AC)=(BA)C=IC=C
so a matrix can have at most one multiplicative inverse.
When such A does hace B so taht AB=BA=I, A is nonsingular or inversible.
*** 初等矩阵
对Identity Matrix做初等行变换
**** 如何求矩阵逆
用等大Identity Matrix增广它，然后让它变成Identity Matrix，旁边那个就是逆
**** diagonal and triangular matrices
- Def
  An $n\times n$ matrix A is said to be upper triangular if $a_{ij}=0$ for $i>j$ and lower triangular if $a_{ij}=0$ for $i<j$. Also, A is said to be triangular if it is either upper triangular or lower triangular.
  An $n\times n$ matrix A is disgonal if $a_{ij}=0$ whenever $i\neq j$.
- A diagonal matrix is both upper triangular and lower triangular.
**** LU factorization
lower+upper triangular factorization
**** partitioned matrices分块矩阵
* Vector Spaces
** definition and examples
*** euclidean vector space欧几里得向量空间
$\mathbb{R}^n,\,n=1,2,...$
*** vector space axioms公理
let V be a *set* on which the operations of *addition* and *scalar* multiplication are defined.
By this we mean that, with each pair of elements x and y in V, we can associate a unique element x+y that is also in V, and with each element x in V and each scalar \alpha, we can associate a unique element ax in V.
The set V together with the operations of addition and scalar multiplication is said to form a vector space if the following axioms are satisfied:
1. x+y=y+x for any x and y in V
2. (x+y)+z=x+(y+z) for any x, y and z in V.
3. there exists an element 0 in V such that x+0=x for each x\in V
4. for each x\in V, there exists an element -x in V such that x+(-x)=0
5. \alpha(x+y)=\alpha x+\alpha y for each scalar \alpha and any x,y in V
6. (\alpha+\beta)x=\alpha x + \beta x for any \alpha and \beta and each x in V
7. 
8. 

**** -
the set V is the _universal set_ for the vector space.
Its elements are _called vectors_ and are usually denoted by voldface latters such as *u*, *v*, *x*, *y* and *z*.
the term _scalar_ will generally refer a real number (maybe complex numbers in some situations)
the term _real vector space_ is used to indicate that the set of scalars is the set of real numbers (not refering to the elements!)
the boldface symbol *0* was used in axion 3 in order to distinguish the zero vector from the scalar 0
**** the closure properties
1. if x \in V and \alpha is a scalar, then \alpha x \in V
2. if x,y \in V then x+y \in V

*** P_n
let P_n denote the set of all polyunomials多项式 of degree less than n. Define p+q and ap, respectively by
$$ (p+q)(x)=p(x)+q(x) $$
and
$$ (ap)(x)=ap(x) $$
for all real numbers x
in this case, the zero vector is the zero polunomial
$$ z(x)=0x^{n-1}+0x^{n-2}+...+0x+0 $$

** subspaces
must be closed uder the operations of addition and scalar multiplication
*** remarks
1. in a vector space V, it can be readily varified that {*0*} and V are subspaces of V
   all other subspaces are referred to as proper subspaces
   we refer to {*0*} as the zero subspace
2. to show that a subset S of a vector space forms a subspace, we must show that S is nonempty and that the closure properties (i) and (ii) in the definition are satisfied...
*** null space of a matrix合空间
注意，叫null却是所有线性方程组解的集合
let A be an $m\times n$ matrix
let N(A) denote the set of all solutions to the homogeneous system Ax=0
thus N(A)={x\in R^n | Ax=0}
**** claim: N(A) is a subspace of R^n
**** 基向量
*** linearly independent
- def
  $c_1\vec{v_1} + ... + c_n\vec{v_n} = \vec{0}$
- basis基
  a minimal spanning set is called a basis
*** v1-vn is a spanning set for a vector space V
then any collection of m vectors in V, where m>n, is linearly dependent
*** base基
1. linearly independent
2. spans V
   
number of base -> dimension
**** subspace {0} of V
defined to have dimension 0
**** finite dimentional
have a finite set of vectors that spans V
**** infinite dimentional
otherwise the above one
**** standard basis
${v_1,v_2.v_3}$
because it is natural to be used in $\mathbb{R}^3$
*** transition matrix转移矩阵（过渡矩阵）
怎么求？
*** change of basis for a general vector space
- def
  let V be a vector space and let $E={v_1,v_2,...,v_n}$ be an ordered basis for V.
  if v is any element of V, then V can be written in the form
  $v=c_1v_1+...+c_nv_n$ where $c_1,...,c_n$ are scalars
  thus we can associate with each vector $v$ a *unique* vector $c$
** 2 row equivalent matrices have the same row space
- def
  the rank秩 of a matrix A, denoted rank(A), is the dimension of the row space of A
*** how to determine the rank?
we can reduce the matrix to row echelon form
then the nonzero rows of the row echelon matrix will form a basis for the row space
** Linear Systems
*** consistency theorem for linear system
A linear system Ax=b is consistent if and only if b is in the column space of A
**** theorem
Let A be an m\times n matrix
the linear system Ax=b is consistent for every
b \in \mathbb{R}^m if and only if the column vectors of A span \mathbb{R}^m
the system Ax=b has at most one solution for every b \in \mathbb{R}^m
if and only if the column vectors of A are linearly independent
**** corollary
an x\times n matrix A is nonsignular if and only if the column vectors form a basis for \mathbb{R}^m
*** the Rank Nullity theorem
if A is an mxn matrix, then the rank of A plis ther nullity零度 of A equals n
