#+TITLE: Linear Algebra Assignment 2
#+AUTHOR: 2024110144
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper,12pt]
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+LATEX_HEADER: \pdfcompresslevel=9
#+OPTIONS: \n:t toc:nil num:nil date:nil

#+begin_center
Please submit by 5:00 PM on April 3rd to the email address: 2592793289@qq.com
#+end_center

* Problem 1
Solve the following system of linear equations and compute the matrix operations.
Let
$$A=\left(\begin{matrix}
2 & -1 & 3\\
0 & 4 & -2\\
1 & 5 & 0
\end{matrix}\right)
\quad
B=\left(\begin{matrix}
-1 & 2 & 0\\
3 & 2 & 1\\
4 & 0 & -3
\end{matrix}\right)$$
Compute:
1. $3A$
2. $A-2B$
3. $(3A)^T-(2B)^T$
4. $AB$
5. $BA$
** Solution 1
*** 1
$$3A=\left(\begin{matrix}
6 & -3 & 9\\
0 & 12 & -6\\
3 & 15 & 0
\end{matrix}\right)$$
*** 2
$$\begin{aligned}
A-2B &= \left(\begin{matrix}
2 & -1 & 3\\
0 & 4 & -2\\
1 & 5 & 0
\end{matrix}\right) - 2 \cdot \left(\begin{matrix}
-1 & 2 & 0\\
3 & 2 & 1\\
4 & 0 & -3
\end{matrix}\right)\\
&= \left(\begin{matrix}
2 & -1 & 3\\
0 & 4 & -2\\
1 & 5 & 0
\end{matrix}\right) - \left(\begin{matrix}
-2 & 4 & 0\\
6 & 4 & 2\\
8 & 0 & -6
\end{matrix}\right)\\
&= \left(\begin{matrix}
4 & -5 & 3\\
-6 & 0 & -4\\
-7 & 5 & 6
\end{matrix}\right)
\end{aligned}$$
*** 3
$$\begin{aligned}
(3A)^T-(2B)^T &= \left(\begin{matrix}
6 & -3 & 9\\
0 & 12 & -6\\
3 & 15 & 0
\end{matrix}\right)^T - \left(\begin{matrix}
-2 & 4 & 0\\
6 & 4 & 2\\
8 & 0 & -6
\end{matrix}\right)^T\\
&= \left(\begin{matrix}
6 & 0 & 3\\
-3 & 12 & 15\\
9 & -6 & 0
\end{matrix}\right) - \left(\begin{matrix}
-2 & 6 & 8\\
4 & 4 & 0\\
0 & 2 & -6
\end{matrix}\right)\\
&= \left(\begin{matrix}
8 & -6 & -5\\
-7 & 8 & 15\\
9 & -8 & 6
\end{matrix}\right)
\end{aligned}$$
*** 4
$$\begin{aligned}
AB &= \left(\begin{matrix}
2 & -1 & 3\\
0 & 4 & -2\\
1 & 5 & 0
\end{matrix}\right) \cdot \left(\begin{matrix}
-1 & 2 & 0\\
3 & 2 & 1\\
4 & 0 & -3
\end{matrix}\right)\\
&= \left(\begin{matrix}
(2\times -1+(-1)\times 3+3\times 4) & (2\times 2+(-1)\times 2+3\times 0) & (2\times 0+(-1)\times 1+3\times (-3))\\
(0\times -1+4\times 3+(-2)\times 4) & (0\times 2+4\times 2+(-2)\times 0) & (0\times 0+4\times 1+(-2)\times (-3))\\
(1\times -1+5\times 3+0\times 4) & (1\times 2+5\times 2+0\times 0) & (1\times 0+5\times 1+0\times (-3))
\end{matrix}\right)\\
&= \left(\begin{matrix}
7 & 2 & -10\\
4 & 8 & 10\\
14 & 12 & 5
\end{matrix}\right)
\end{aligned}$$
*** 5
$$\begin{aligned}
BA &= \left(\begin{matrix}
-1 & 2 & 0\\
3 & 2 & 1\\
4 & 0 & -3
\end{matrix}\right) \cdot \left(\begin{matrix}
2 & -1 & 3\\
0 & 4 & -2\\
1 & 5 & 0
\end{matrix}\right)\\
&= \left(\begin{matrix}
(-1\times 2+2\times 0+0\times 1) & (-1\times (-1)+2\times 4+0\times 5) & (-1\times 3+2\times (-2)+0\times 0)\\
(3\times 2+2\times 0+1\times 1) & (3\times (-1)+2\times 4+1\times 5) & (3\times 3+2\times (-2)+1\times 0)\\
(4\times 2+0\times 0+(-3)\times 1) & (4\times (-1)+0\times 4+(-3)\times 5) & (4\times 3+0\times (-2)+(-3)\times 0)
\end{matrix}\right)\\
&= \left(\begin{matrix}
-2 & 9 & -7\\
7 & 10 & 5\\
5 & -19 & 12
\end{matrix}\right)
\end{aligned}$$

* Problem 2
Let $M$ be an $n\times n$ matrix. Define
$$S=\frac{1}{2} (M+M^T) \,\text{and}\, K=\frac{1}{2} (M-M^T)$$.
Prove that:
1. $S$ is symmetric.
2. $K$ is skew-symmetric, i.e. $K^T=-K$.
3. $M=S+K$.
** Solution 2
*** 1
for $i,j \in {1,2,...,n}$
$S_{ij} = \frac{1}{2} (M_{ij}+M_{ji}) = S_{ji}$
so $S$ is symmetric
*** 2
for $i,j \in {1,2,...,n}$
$K_{ii}=0$
and $K_{ij} = \frac{1}{2} (M_{ij}-M_{ji}) = -K_{ji}$
so $K$ is skew-symmetric
*** 3
for $i,j \in {1,2,...,n}$
we know $(S+K)_{ij} = \frac{1}{2} (M_{ij}+M_{ji}) + \frac{1}{2} (M_{ij}-M_{ji}) = M_{ij}$
so $M=S+K$

* Problem 3
Let $A$ be an $n\times n$ idempotent matrix (i.e. $A^2=A). Prove that
$$H=I-2A$$
is an involution; that is, show that $H^2=I$.
** Solution 3
we need to show that $(I-2A)^2=I$ for $A^2=A$
the left part is $I^2-2IA-2AI+4A^2$
which is just $I-4A+4A^2$
since $A^2=A$, it is obvious that this is equal to $I$

* Problem 4
Let
$$A=\left(\begin{matrix}
1 & 2 & 3\\
4 & 5 & 6
\end{matrix}\right),
\quad
B=\left(\begin{matrix}
1 & 2 & 3\\
0 & 1 & 4\\
5 & 6 & 0
\end{matrix}\right),
\quad
C=\left(\begin{matrix}
2 & -1\\
0 & 3\\
1 & 1
\end{matrix}\right).$$
Compute the product $ABC$.
** Solution 4
first let's compute $BC$
$$\begin{aligned}
BC &= \left(\begin{matrix}
1 & 2 & 3\\
0 & 1 & 4\\
5 & 6 & 0
\end{matrix}\right) \cdot \left(\begin{matrix}
2 & -1\\
0 & 3\\
1 & 1
\end{matrix}\right)\\
&= \left(\begin{matrix}
(1\times 2+2\times 0+3\times 1) & (1\times (-1)+2\times 3+3\times 1)\\
(0\times 2+1\times 0+4\times 1) & (0\times (-1)+1\times 3+4\times 1)\\
(5\times 2+6\times 0+0\times 1) & (5\times (-1)+6\times 3+0\times 1)
\end{matrix}\right)\\
&= \left(\begin{matrix}
5 & 8\\
4 & 7\\
10 & 13
\end{matrix}\right)
\end{aligned}$$
then we finish the multiplication with $A$
$$\begin{aligned}
A \cdot \left(\begin{matrix}
5 & 8\\
4 & 7\\
10 & 13
\end{matrix}\right) &= \left(\begin{matrix}
1 & 2 & 3\\
4 & 5 & 6
\end{matrix}\right) \cdot \left(\begin{matrix}
5 & 8\\
4 & 7\\
10 & 13
\end{matrix}\right)\\
&= \left(\begin{matrix}
(1\times 5+2\times 4+3\times 10) & (1\times 8+2\times 7+3\times 13)\\
(4\times 5+5\times 4+6\times 10) & (4\times 8+5\times 7+6\times 13)
\end{matrix}\right)\\
&= \left(\begin{matrix}
43 & 61\\
100 & 145
\end{matrix}\right)
\end{aligned}$$

* Problem 5
Given
$$A=\left(\begin{matrix}
2 & 3 & 1\\
4 & 7 & 3\\
6 & 11 & 7
\end{matrix}\right)$$,
1. Perform Gaussian elimination (without pivoting) to find elementary matrices
   $$E_1,E_2,E_3$$
   such that
   $$E_3E_2E_1A=U$$,
   where $U$ is an upper triangular matrix.
2. Compute the inverse $E_1^{-1},E_2^{-1},E_3^{-1}$, define
   $$L=E_1^{-1}E_2^{-1}E_3^{-1}$$,
   and verify that $A=LU$.
** Solution 5
*** 1
first we shall calculate $E_1$
$$\left[\begin{array}{ccc|ccc}
2 & 3 & 1 & 1 & 0 & 0\\
4 & 7 & 3 & 0 & 1 & 0\\
6 & 11 & 7 & 0 & 0 & 1
\end{array}\right]$$
$$\left[\begin{array}{ccc|ccc}
2 & 3 & 1 & 1 & 0 & 0\\
0 & 1 & 1 & -2 & 1 & 0\\
6 & 11 & 7 & 0 & 0 & 1
\end{array}\right]$$
$$\left[\begin{array}{ccc|ccc}
2 & 3 & 1 & 1 & 0 & 0\\
0 & 1 & 1 & -2 & 1 & 0\\
0 & 2 & 4 & -3 & 0 & 1
\end{array}\right]$$
$$\left[\begin{array}{ccc|ccc}
2 & 3 & 1 & 1 & 0 & 0\\
0 & 1 & 1 & -2 & 1 & 0\\
0 & 0 & 2 & 1 & -2 & 1
\end{array}\right]$$
so
$$E_1=\left(\begin{matrix}
1 & 0 & 0\\
-2 & 1 & 0\\
1 & -2 & 1
\end{matrix}\right)$$
then we calculate $E_2$
$$\left[\begin{array}{ccc|ccc}
1 & 0 & 0 & 1 & 0 & 0\\
-2 & 1 & 0 & 0 & 1 & 0\\
1 & -2 & 1 & 0 & 0 & 1
\end{array}\right]$$
$$\left[\begin{array}{ccc|ccc}
1 & 0 & 0 & 1 & 0 & 0\\
0 & 1 & 0 & 2 & 1 & 0\\
1 & -2 & 1 & 0 & 0 & 1
\end{array}\right]$$
$$\left[\begin{array}{ccc|ccc}
1 & 0 & 0 & 1 & 0 & 0\\
0 & 1 & 0 & 2 & 1 & 0\\
0 & -2 & 1 & -1 & 0 & 1
\end{array}\right]$$
$$\left[\begin{array}{ccc|ccc}
1 & 0 & 0 & 1 & 0 & 0\\
0 & 1 & 0 & 2 & 1 & 0\\
0 & 0 & 1 & 3 & 2 & 1
\end{array}\right]$$
so
$$E_2=\left(\begin{matrix}
1 & 0 & 0\\
2 & 1 & 0\\
3 & 2 & 1
\end{matrix}\right)$$
then we calculate $E_3$
$$\left[\begin{array}{ccc|ccc}
1 & 0 & 0 & 1 & 0 & 0\\
2 & 1 & 0 & 0 & 1 & 0\\
3 & 2 & 1 & 0 & 0 & 1
\end{array}\right]$$
$$\left[\begin{array}{ccc|ccc}
1 & 0 & 0 & 1 & 0 & 0\\
0 & 1 & 0 & -2 & 1 & 0\\
3 & 2 & 1 & 0 & 0 & 1
\end{array}\right]$$
$$\left[\begin{array}{ccc|ccc}
1 & 0 & 0 & 1 & 0 & 0\\
0 & 1 & 0 & -2 & 1 & 0\\
0 & 2 & 1 & -3 & 0 & 1
\end{array}\right]$$
$$\left[\begin{array}{ccc|ccc}
1 & 0 & 0 & 1 & 0 & 0\\
0 & 1 & 0 & -2 & 1 & 0\\
0 & 0 & 1 & 1 & -2 & 1
\end{array}\right]$$
so
$$E_3=\left(\begin{matrix}
1 & 0 & 0\\
-2 & 1 & 0\\
1 & -2 & 1
\end{matrix}\right)$$
*** 2
the inverse of $E_1$ is $E_2$, and that of $E_2$ is $E_3$, which is equal to $E_1$
then we know $L=E_2$
then $LU=LE_3E_2E_1A=LE_1A=IA=A$
